=== Dukawp/PRI-2019/TPC 2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project-record (info,work-team,abstract,deliverables) >

<!ELEMENT info (key-name,title,subtitle,begin-date,end-date,supervisor) >

<!ELEMENT key-name      (#PCDATA) >
<!ELEMENT title         (#PCDATA) >
<!ELEMENT subtitle      (#PCDATA) >
<!ELEMENT begin-date    (#PCDATA) >
<!ELEMENT end-date      (#PCDATA) >
<!ELEMENT supervisor    (#PCDATA) >

<!ELEMENT work-team     (member)+ >
<!ELEMENT member        (#PCDATA) >

<!ELEMENT abstract      (paragraph)+ >
<!ELEMENT paragraph     (#PCDATA) >

<!ELEMENT deliverables  (deliverable)* >
<!ELEMENT deliverable   (#PCDATA) >

<!ATTLIST supervisor 
            link        CDATA #REQUIRED >

<!ATTLIST member 
            link        CDATA #REQUIRED >
            
<!ATTLIST paragraph 
            link        CDATA #IMPLIED
            bold        CDATA #IMPLIED
            italic      CDATA #IMPLIED >            
            
<!ATTLIST deliverable
            link CDATA #REQUIRED >

=== Dukawp/PRI-2019/TPC 2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "file:/C:/Users/Duka_/Desktop/PLC/PRI/TPC/TPC2/pr.dtd">
<project-record>
    <info>
        <key-name></key-name>
        <title></title>
        <subtitle></subtitle>
        <begin-date></begin-date>
        <end-date></end-date>
        <supervisor link=""></supervisor>
    </info>
    <work-team>
        <member link=""></member>
    </work-team>
    <abstract>
        <paragraph></paragraph>
    </abstract>
    <deliverables>
        <deliverable link=""></deliverable>
    </deliverables>
</project-record>
