=== Dukawp/PRI-2019/TPC 3/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (meta, workteam, abstract, deliverables) >

<!ELEMENT meta (keyname, title, subtitle?, bdate, edate, supervisor) >
<!ELEMENT keyname           (#PCDATA) >
<!ELEMENT title             (#PCDATA) >
<!ELEMENT subtitle          (#PCDATA) >
<!ELEMENT bdate             (#PCDATA) >
<!ELEMENT edate             (#PCDATA) >

<!ELEMENT supervisor (name, email?, homepage?) >
<!ELEMENT name              (#PCDATA) >
<!ELEMENT email             (#PCDATA) >
<!ELEMENT homepage          (#PCDATA) >


<!ELEMENT workteam (member+) >
<!ELEMENT member (identifier, name, email, photo?) >
<!ELEMENT identifier        (#PCDATA) >
<!ELEMENT photo              EMPTY  >


<!ATTLIST photo 
            path             CDATA #REQUIRED>

<!ELEMENT abstract (p+) >
<!ELEMENT p                 (#PCDATA|b|i|u|xref)* >
<!ELEMENT b                 (#PCDATA|i|u|xref)* >
<!ELEMENT i                 (#PCDATA|b|u|xref)* >
<!ELEMENT u                 (#PCDATA|b|i|xref)* >

<!ELEMENT xref              (#PCDATA) >
<!ATTLIST xref
            url              CDATA #REQUIRED>


<!ELEMENT deliverables (deliverable+) >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable 
            path             CDATA #REQUIRED>

=== Dukawp/PRI-2019/TPC 3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "file:/C:/Users/Duka_/Desktop/PLC/PRI/TPC/TPC3/pr.dtd">
<pr>
    <meta>
        <keyname>PRI2019-A63129-T3</keyname>
        <title>Elaboração de Website sobre Arqueositios </title>
        <subtitle>Trabalho prático número três da UC PRI</subtitle>
        <bdate>07-10-2019</bdate>
        <edate>21-10-2019</edate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminho.pt</email>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
    </meta>
    <workteam>
        <member>
            <identifier>A63129</identifier>
            <name>Duarte Freitas</name>
            <email>a63129@alunos.uminho.pt</email>
            <photo path="images\cv.jpeg"/>
        </member>
    </workteam>
    <abstract>
        <p>
            Elaboração do <b>XML</b> e posteriormente do <b>XSL</b> para o desenvolvimento desta pagina web  
        </p>
        <p>
            Desenvolvimento do <b>XSL</b> para gerar paginas web com o conteudos do <b>XML</b> sobre <b>Arqueositios</b>
        </p>
       
    </abstract>
    <deliverables>
        <deliverable path="pr.xml">XML do Project Record</deliverable>
        <deliverable path="pr.xsl">XSL do Project Record</deliverable>
        <deliverable path="pr.html">HTML do Project Record</deliverable>
        <deliverable path="arq.xsl">XSL do Arqueositios</deliverable>
        <deliverable path="website/index.html">Indice HTML do Arqueositios</deliverable>
    </deliverables>
</pr>
